### PR TITLE
[WORKFLOWS-68] Use Sceptre template handlers for remote templates

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
As I was preparing this PR, I noticed that the new template handlers haven't made it into a new Sceptre release. It's currently only on the `master` branch. I think we should wait until a new release is minted. 

@zaro0508: Do you know when we should expect a new Sceptre release?

### CODE REVIEW

**Comment by zaro0508** [comment]
We are planning on a new release next week @BrunoGrandePhD

**Review by zaro0508 — APPROVED** [review]

**Comment by zaro0508** [comment]
[Sceptre v2.7.0](https://pypi.org/project/sceptre/), which contains the [template handler](https://sceptre.cloudreach.com/2.7.0/docs/template_handlers.html) feature has been released.

**Review by tthyer — APPROVED** [review]

**Comment by BrunoGrandePhD** [comment]
Thanks for the heads-up, @zaro0508! I just pushed an update to our Pipfile, but I'm going to have to wait before merging because it's going to have merge conflicts with #77. I'll see which one I'll merge depending on which one gets the approvals I'm seeking first.

**Comment by BrunoGrandePhD** [comment]
I guess it's this PR then! Thanks, @tthyer!

**Pull request merged**
