### PR TITLE
[WORKFLOWS-66] Allow S3 object indexing by Synapse

### PR DESCRIPTION
**Pull request by BrunoGrandePhD**
This is the first step to allowing the Tower project buckets to be used as is for indexing files in Synapse. 

I'm also updating all Tower project configs to use this new feature. I'll confirm with the config "owners" whether this is a desired change. Tracked below:

- [x] amp-ad-project.yaml
- [x] challenge-infra-test-project.yaml
- [x] htan-project.yaml
- [x] imcore-project.yaml
- [x] jhu-biobank-nf-project.yaml

## Example Code

I used the following code to test that I can index S3 objects in Synapse. Note that you need to create an object called `owner.txt` in the root of the bucket for Synapse to recognize the external location. This can be done downstream by a script that has S3 and Synapse credentials. 

```python
# Import packages
import synapseclient
import json

# Create custom storage location (owner.txt must exist at this stage)
syn = synapseclient.login()
destination = {
    "uploadType": "S3",
    "concreteType": "org.sagebionetworks.repo.model.project.ExternalS3StorageLocationSetting",
    "bucket": "example-dev-project-tower-bucket",
}
destination = syn.restPOST("/storageLocation", body=json.dumps(destination))

# Create a file handle for an S3 object
fileHandle = {
    "concreteType": "org.sagebionetworks.repo.model.file.S3FileHandle",
    "storageLocationId": destination["storageLocationId"],
    "bucketName": destination["bucket"],
    "key": "TCRB-WEX/tcrb-samples-sarek.tsv",
    "fileName": "tcrb-samples-sarek.tsv",
    "contentMd5": "a25ba594d3c39a5eab8d02d6deee6e87",
    # "contentSize": "382",                         # Optional
    # "contentType": "text/tab-separated-values",   # Optional
}
fileHandle = syn.restPOST(
    "/externalFileHandle/s3", json.dumps(fileHandle), endpoint=syn.fileHandleEndpoint
)

# Expose that file handle on Synapse with a File
f = synapseclient.File(
    name=fileHandle["fileName"],
    parentId="syn23529995",
    dataFileHandleId=fileHandle["id"],
)
f = syn.store(f)
```

### CODE REVIEW

**Comment by BrunoGrandePhD** [comment]
@thomasyu888 Two questions for you:

1. Are you okay with me deleting the Challenge project in projects-dev? You can do any testing in Nextflow-prod .
2. Are you okay with allowing Synapse indexing on your non-dev Challenge project?

**Comment by thomasyu888** [comment]
Yes to both @BrunoGrandePhD

**Comment by BrunoGrandePhD** [comment]
@wpoehlm: Would it be useful for you to have the ability to index objects uploaded to the AMP-AD bucket in Synapse?

**Review by tthyer — APPROVED** [review]
LGTM. 
Do you want to think about editing the project template to automatically add the owner.txt? I've fixed the s3object macro and have an example where I've done this in BridgeDownstream. We have a script to set up external storage too, but right now I run that as an after_launch hook.

**Comment by wpoehlm** [comment]
> 
> 
> @wpoehlm: Would it be useful for you to have the ability to index objects uploaded to the AMP-AD bucket in Synapse?

Yes, this would be useful particularly if we don't have automated output uploads built into the workflows

**Comment by BrunoGrandePhD** [comment]
@tthyer: Because indexing and annotating workflow outputs in Synapse will need to be done by an external script that has access to both AWS and Synapse, I was thinking of deferring the creation of the `owner.txt` file until that point. That way, we keep our template relatively simple for the purposes of creating a library repository. And as you've mentioned before, I hesitate to ask for both AWS and Synapse identities in our Tower project configs. 

Another issue with having us (_i.e._ a CI service account) create the `owner.txt` file and register the external storage location with Synapse is that only the creator of the `ExternalS3StorageLocationSetting` can create `S3FileHandle` objects for that storage location. So, users will have to create their own `ExternalS3StorageLocationSetting` anyways. 

> Only the user that created to the ExternalS3StorageLocationSetting will be allowed to create S3FileHandle using that storageLocationId. ([Source](https://rest-docs.synapse.org/rest/POST/externalFileHandle/s3.html))

**Comment by BrunoGrandePhD** [comment]
Because I want Aaron to help with a review of our Tower project template, I'm going to proceed with merging, but we can continue the conversation of using the `s3objects` macro for creating the `owner.txt` file. If we decide to pursue this approach, I can open a separate PR.

**Pull request merged**
