### PR TITLE
[IT-2376] Remove LaunchConfiguration

### PR DESCRIPTION
**Pull request by zaro0508**
We can remove LaunchConfiguration after switching to LaunchTemplate

depends on #170

### CODE REVIEW

**Review by thomasyu888 — APPROVED** [review]
💯 thanks!

**Comment by BrunoGrandePhD** [comment]
Is there a reason why this is separate from #170?

**Review by BrunoGrandePhD — COMMENTED** [review]
Is there a reason why this is separate from #170?

**Comment by zaro0508** [comment]
> Is there a reason why this is separate from #170?

The difference is an in place replace vs an add then remove workflow.  I prefer the latter when changing resources resources that contain dependencies, it makes it easier to identify issues and rollback if needed.

**Review by BrunoGrandePhD — APPROVED** [review]

**Pull request merged**
